<?php
// +----------------------------------------------------------------------
// | OpenCMF [ Simple Efficient Excellent ]
// +----------------------------------------------------------------------
// | Copyright (c) 2014 http://www.opencmf.cn All rights reserved.
// +----------------------------------------------------------------------
// | Author: jry <598821125@qq.com>
// +----------------------------------------------------------------------
return array(
    'status'=>array(
        'title'=>'支付总开关',
        'type'=>'radio',
        'options'=>array(
            '1'=>'开启',
            '0'=>'关闭',
        ),
        'value'=>'1',
    ),
    'allow_pay_type'=>array(
        'title'=>'启用的支付方式',
        'type'=>'checkbox',
        'options'=>array(
            'alipay'    => '支付宝',
            'nowpay'    => '现在支付',
            'wxpay'     => '微信支付',
            'unionpay'  => '银联支付',
            'tenpay'    => '财付通',
            'paypal'    => '贝宝paypal',
            'kuaiqian'  => '快钱支付',
            'yeepay'    => '易宝支付',
            'bbnpay'    => 'H5网页收银台',
        ),
        'value'=>'',
    ),
    'group'=>array(
        'type'=>'group',
        'options'=>array(
            'alipay'=>array(
                'title'=>'支付宝',
                'options'=>array(
                    'alipay_email'=>array(
                        'title'=>'支付宝账户',
                        'type'=>'text',
                        'value'=>'25',
                        'tip'=>'一般为邮箱',
                    ),
                    'alipay_partner'=>array(
                        'title'=>'partner',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'类似：2088911710861332',
                    ),
                    'alipay_key'=>array(
                        'title'=>'MD5Key',
                        'type'=>'text',
                        'value'=>'',
                    ),
                    'alipay_private_key'=>array(
                        'title'=>'RSA私钥',
                        'type'=>'textarea',
                        'value'=>'',
                    ),
                    'alipay_ali_public_key'=>array(
                        'title'=>'支付宝公钥',
                        'type'=>'textarea',
                        'value'=>'',
                    ),
                ),
             ),
            'nowpay'=>array(
                'title'=>'现在支付',
                'options'=>array(
                    'nowpay_appid'=>array(
                        'title'=>'appid',
                        'type'=>'text',
                        'tip'=>'pc支付用的appid',
                    ),
                    'nowpay_key'=>array(
                        'title'=>'Key',
                        'type'=>'text',
                        'tip'=>'pc支付用的secure_key',
                    ),
                    'nowpay_wap_appid'=>array(
                        'title'=>'wap_appid',
                        'type'=>'text',
                        'tip'=>'wap支付用的appid',
                    ),
                    'nowpay_wap_key'=>array(
                        'title'=>'wap_Key',
                        'type'=>'text',
                        'tip'=>'wap支付用的secure_key',
                    ),
                    'nowpay_app_appid'=>array(
                        'title'=>'app_appid',
                        'type'=>'text',
                        'tip'=>'app支付用的appid',
                    ),
                    'nowpay_app_key'=>array(
                        'title'=>'app_Key',
                        'type'=>'text',
                        'tip'=>'app支付用的secure_key',
                    ),
                )
            ),
             'wxpay'=>array(
                'title'=>'微信支付',
                'options'=>array(
                    'wxpay_appid'=>array(
                        'title'=>'appid',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'appid',
                    ),
                    'wxpay_appsecret'=>array(
                        'title'=>'appsecret',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'appsecret',
                    ),
                    'wxpay_mchid'=>array(
                        'title'=>'商户ID',
                        'type'=>'text',
                        'value'=>'',
                    ),
                    'wxpay_key'=>array(
                        'title'=>'Key',
                        'type'=>'text',
                        'value'=>'',
                    ),
                ),
             ),
             'wxapppay'=>array(
                'title'=>'微信支付(APP)',
                'options'=>array(
                    'wxapppay_appid'=>array(
                        'title'=>'appid',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'appid',
                    ),
                    'wxapppay_appsecret'=>array(
                        'title'=>'appsecret',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'appsecret',
                    ),
                    'wxapppay_mchid'=>array(
                        'title'=>'商户ID',
                        'type'=>'text',
                        'value'=>'',
                    ),
                    'wxapppay_key'=>array(
                        'title'=>'Key',
                        'type'=>'text',
                        'value'=>'',
                    ),
                ),
             ),
            'unionpay'=>array(
                'title'=>'银联支付',
                'options'=>array(
                    'unionpay_partner'=>array(
                        'title'=>'partner',
                        'type'=>'text',
                        'value'=>'',
                    ),
                    'unionpay_key'=>array(
                        'title'=>'Key',
                        'type'=>'text',
                        'value'=>'',
                    ),
                )
            ),
            'tenpay'=>array(
                'title'=>'财付通',
                'options'=>array(
                    'tenpay_partner'=>array(
                        'title'=>'partner',
                        'type'=>'text',
                        'value'=>'',
                    ),
                    'tenpay_key'=>array(
                        'title'=>'Key',
                        'type'=>'text',
                        'value'=>'',
                    ),
                )
            ),
            'paypal'=>array(
                'title'=>'贝宝paypal',
                'options'=>array(
                    'paypal_business'=>array(
                        'title'=>'paypal账户',
                        'type'=>'text',
                        'value'=>'',
                    ),
                )
            ),
            'kuaiqian'=>array(
                'title'=>'快钱支付',
                'options'=>array(
                    'kuaiqian_partner'=>array(
                        'title'=>'partner',
                        'type'=>'text',
                        'value'=>'',
                    ),
                    'kuaiqian_key'=>array(
                        'title'=>'Key',
                        'type'=>'text',
                        'value'=>'',
                    ),
                )
            ),
            'yeepay'=>array(
                'title'=>'易宝支付',
                'options'=>array(
                    'yeepay_partner'=>array(
                        'title'=>'partner',
                        'type'=>'text',
                    ),
                    'yeepay_key'=>array(
                        'title'=>'Key',
                        'type'=>'text',
                    ),
                )
            ),
            'bbnpay'=>array(
                'title'=>'H5网页收银台',
                'options'=>array(
                    'bbnpay_appid'=>array(
                        'title'=>'appid',
                        'type'=>'text',
                    ),
                    'bbnpay_appkey'=>array(
                        'title'=>'appkey',
                        'type'=>'text',
                    ),
                )
            ),
        )
    )
);
